apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.8.2         # check the latest version
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    # You can customize install settings here, e.g. creating CRDs, etc.
