apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-registry-harbor-docker-login
  # Namespace will be overridden in overlays
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: default-registry-harbor-docker-login
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .registryName | lower }}.{{ .registryHost }}":{"username":"{{ .registryName }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .registryName .password | b64enc }}"}}}'
  data:
    - secretKey: docker-server
      remoteRef:
        key: k3s_harbor_docker_pull_default
        property: registry
    - secretKey: docker-username
      remoteRef:
        key: k3s_harbor_docker_pull_default
        property: username
    - secretKey: docker-password
      remoteRef:
        key: k3s_harbor_docker_pull_default
        property: password
    - secretKey: docker-email
      remoteRef:
        key: k3s_harbor_docker_pull_default
        property: email
