# /apps/base/my-app/my-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  namespace: personal-site
spec:
  replicas: 3
  selector:
      matchLabels:
        app: personal-site
  template:
      metadata:
          labels:
            app: personal-site
      spec:
        imagePullSecrets:
          # This is the secret for the personal-site registry
          - name: personal-site-registry-harbor-docker-login

        containers:
          - name: personal-site
            image: harbor.internal/personal-blog/astro-ssr:latest
            ports:
              - containerPort: 80
