apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuers
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/resources/clusterissuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager  # Ensure Cert-Manager is installed first
