apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  # TODO set to 10m
  interval: 1m
  path: ./cluster/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
