apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-docker-login
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: harbor-docker-login
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf \"%s:%s\" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - key: k3s_harbor_docker_pull
