# This secret is specifically for the personal-site registry
# So we don't need to template it or overlay it
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: personal-site-registry-harbor-docker-login
  namespace: personal-site
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: personal-site-registry-harbor-docker-login
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .data.docker-server }}": {
                "username": "{{ .data.docker-username }}",
                "password": "{{ .data.docker-password }}",
                "email": "{{ .data.docker-email }}",
                "auth": "{{ printf \"%s:%s\" .data.docker-username .data.docker-password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: docker-server
      remoteRef:
        key: k3s_harbor_docker_pull_personal_site
        property: registry
    - secretKey: docker-username
      remoteRef:
        key: k3s_harbor_docker_pull_personal_site
        property: username
    - secretKey: docker-password
      remoteRef:
        key: k3s_harbor_docker_pull_personal_site
        property: password
    - secretKey: docker-email
      remoteRef:
        key: k3s_harbor_docker_pull_personal_site
        property: email
