apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  path: ./cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
