apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  chart:
    spec:
      # Pinned => update manually
      version: 4.1.0
  values:
    proxy:
      service: ClusterIP
      https:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          kubernetes.io/ingress.class: "traefik"
      hosts:
        - jupyterhub.internal
      tls:
        - secretName: jupyterhub-tls # Cert-Manager will manage this secret
          hosts:
            - jupyterhub.internal
