apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      version: 1.10.0
  interval: 10m
  values:
    externalURL: "http://harbor.local"
    expose:
      type: ingress
      ingress:
        hosts:
          core: harbor.local
        tls:
          enabled: false
