apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  path: ./cluster/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: namespaces  # Ensures namespaces exist before secrets
    - name: external-secrets # Ensure secret store is ready
  interval: 10m
