apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    namespace: external-secrets
    kind: SecretStore
  target:
    name: harbor-admin-password
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: k3s_harbor_admin_password  # AWS Secrets Manager secret name
        property: admin-password
