apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/base/helm-repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
