apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./cluster/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    # Make sure to wait for the namespace to be created before deploying anything
    - name: namespaces
    # Wait for base dependencies
    - name: base
    # Wait for helm repos (part of base)
    - name: helm-repos
