apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  targetNamespace: harbor
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    externalURL: "https://harbor.bennettdixon.dev"

    expose:
      type: ingress
      tls:
        enabled: true
        secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.bennettdixon.dev
          notary: notary.bennettdixon.dev
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"

    persistence:
      persistentVolumeClaim:
        registry:
          size: 50Gi
