# name: Validate Kubernetes Manifests

# on:
# #   push:
# #     branches:
# #       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   validate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Kubeval
#         run: curl -s https://install.kubeval.com | bash

#       - name: Validate manifests
#         run: kubeval cluster/**/*.yaml
